spring:
  jpa:
    hibernate:
      ddl-auto: create # create update none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true

  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://127.0.0.1:3306/oauth2
    username: root
    password: 123456

  security:
    oauth2:
      client:
        registration:
          google:
            client-id:
            client-secret:
            scope: # \uAC01 \uD50C\uB7AB\uD3FC\uC758 \uC0AC\uC6A9\uC790 \uB3D9\uC758\uCCB4\uD06C\uC5D0\uC11C \uC0AC\uC6A9\uC790 \uC815\uBCF4\uC911 \uD544\uC694\uD55C \uC815\uBCF4\uC758 \uD544\uB4DC\uB97C \uB123\uC74C
              - email
              - profile

          naver:
            client-id:
            client-secret:
            scope:
              - name
              - email
              - profile_image
            client-name: Naver
            authorization-grant-type: authorization_code # \uAD8C\uD55C \uBD80\uC5EC \uBC29\uC2DD\uC758 \uC885\uB958\uB85C code, token\uC744 \uC0AC\uC6A9\uD558\uB294 \uBC29\uC2DD
            redirect-uri: http://localhost:8080/login/oauth2/code/naver  #\uCF54\uB4DC\uB97C \uBC1B\uB294 uri(naver \uC758 \uCF5C\uBC31 uri)

          kakao:
            client-id:
            client-secret:
            scope:
              - account_email
              - profile_nickname
              - profile_image
            client-name: Kakao
            authorization-grant-type: authorization_code
            client-authentication-method: POST #\uCE74\uCE74\uC624\uB294 \uD544\uC218 \uD30C\uB77C\uBBF8\uD130\uB97C POST\uB85C \uC694\uCCAD\uD574\uC57C\uD568
            redirect-uri: http://localhost:8080/login/oauth2/code/kakao #\uCF54\uB4DC\uB97C \uBC1B\uB294 uri(naver \uC758 \uCF5C\uBC31 uri)

        provider: #\uB124\uC774\uBC84\uC758 provider\uB294 \uB4F1\uB85D\uB418\uC5B4 \uC788\uC9C0 \uC54A\uC544 \uC0AC\uC6A9\uC790\uAC00 \uB4F1\uB85D\uD574\uC57C\uD568  ( oauth2-client \uC5D0\uC11C \uC81C\uACF5\uD558\uC9C0 \uC54A\uB294 provider \uC815\uC758 )
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize #\uB124\uC774\uBC84 \uB85C\uADF8\uC778 \uCC3D\uC744 \uBC1B\uC744\uC218 \uC787\uB2E4
            token-uri: https://nid.naver.com/oauth2.0/token #\uD1A0\uD070\uC744 \uBC1B\uB294 uri
            user-info-uri: https://openapi.naver.com/v1/nid/me #\uD504\uB85C\uD544 \uC8FC\uC18C\uB97C \uBC1B\uB294 uri
            user-name-attribute: response #\uD68C\uC6D0 \uC815\uBCF4\uB97C json \uD615\uD0DC\uB85C \uBC1B\uB098\uB290\uB370 response \uB77C\uB294 \uD0A4 \uAC12\uC73C\uB85C \uB124\uC774\uBC84\uAC00 \uB9AC\uD134\uD574\uC90C

          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: kakao_account

# \uC2A4\uD504\uB9C1 OAuth2-client \uB77C\uC774\uBE0C\uB7EC\uB9AC\uC758 provider\uC5D0\uB294 \uAD6C\uAE00,\uD398\uC774\uC2A4\uBD81,\uD2B8\uC704\uD130\uAC00 \uC18D\uD574\uC788\uC5B4 redirect-uri, authorization-grant-type\uC744 \uC801\uC5B4\uC8FC\uC9C0 \uC54A\uC544\uB3C4 \uC790\uB3D9\uC73C\uB85C \uB4F1\uB85D\uB418\uC5B4\uC788\uB2E4(\uC801\uC5B4\uC918\uB3C4\uB428)
# \uB124\uC774\uBC84\uB098 \uCE74\uCE74\uC624\uB294 Provider\uAC00 \uC544\uB2C8\uAE30 \uB54C\uBB38\uC5D0 \uC801\uC5B4\uC918\uC57C\uD568, \uC6D0\uD558\uB294\uB300\uB85C uri\uB97C \uC9C0\uC815\uD560\uC218 \uC788\uC74C, \uACE0\uC815\uB418\uC5B4\uC788\uC9C0 \uC54A\uC74C
